version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: u2/server
    container_name: u2-server
    ports:
      - "8080:8080/tcp"
      - "7777:7777/udp"
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: u2/client
    container_name: u2-client
    environment:
      VITE_SERVER_URL: ws://server:8080/
    ports:
      - "5173:5173"
    depends_on:
      - server
    restart: unless-stopped
